version: '2'
services:
  ranialcippg-app:
    image: ranialcippg
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ranialcippg-postgresql:5432/RANIALCIPPG
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true
  ranialcippg-postgresql:
    extends:
      file: postgresql.yml
      service: ranialcippg-postgresql
